name: axe-core Tests

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Run axe
        run: |
          npm install -g @axe-core/cli
          {
            echo 'axe_output<<EOF'
            axe https://beta.gouv.fr --exit 2>&1
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Read result
        if: success() || failure()
        id: unit_test_report
        run: |
          echo "$axe_output"
