name: axe-core Tests

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Run axe
        id: axe
        run: |
          npm install -g @axe-core/cli
          echo "AXE_OUTPUT=$(axe https://beta.gouv.fr)" >> $GITHUB_OUTPUT

      - name: Read result
        if: success() || failure()
        run: |
          echo "$AXE_OUTPUT"
