name: Review env check

on:
  check_run:
    types: [completed]
  check_suite:
    types: [completed]
    
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Hi
      run: echo "io"

